version: "3"
      
volumes:
  db-data:

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - jekyll
    links:
      - jekyll
      - social-blogging
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --watch --drafts
    volumes:
      - .:/srv/jekyll
    environment:
      JEKYLL_ENV: development
  social-blogging:
    links:
      - jekyll
    build:
      context: ../social-blogging
    volumes:
      - db-data:/var/lib/sqlite
    environment:
      - RSS_FEED_URL=http://jekyll:4000/rss.xml
